[fix]フォローされている人リストのボタンの修正完了
Bas4rk/Web_Amplify pull request #19
Opened 2020-12-03 04:29 UTC by WatanabeKeitaa

フォローしている人、していない人を判定して「フォロー」ボタンと「フォロー解除」ボタンの表示を切り替えるようにしました。
ボタンを押した後のcreateRelationとdeleteRelationが正しく動作しないので、とりあえずコメントアウトしました。

2020-12-03 09:28 UTC, Bas4rk commented on src/components/FolloweeList.vue
> +        if(this.followees[k].follower.id == this.user[t].followee.id){
`if(this.followees[k].follower.id == this.user[t].followee.id){`
のところ
`if(this.followees[t].follower.id == this.user[k].followee.id){`
添え字逆？

2020-12-03 09:40 UTC, Bas4rk requested changes
すみませんがコメントの箇所と、master更新してしまったので、fetchして再度お願いします

2020-12-03 13:35 UTC, WatanabeKeitaa commented
masterをfetchしてmergeしてから、添え字の指摘箇所を修正しました。よく考えたら逆でした。
FolloweeList.vue内の使わなくなったり、重複していた変数とか配列を削除しました。
今回修正した変更箇所にコメントを書いてなかったので書きました。

2020-12-04 04:09 UTC, Bas4rk approved these changes
確認しました

2020-12-04 04:09 UTC, merged